2017-12-14T11:33:02.729531+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
2017-12-14T11:33:02.729531+00:00 app[web.1]:     self.load_wsgi()
2017-12-14T11:33:02.729532+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
2017-12-14T11:33:02.729532+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2017-12-14T11:33:02.729533+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
2017-12-14T11:33:02.729533+00:00 app[web.1]:     self.callable = self.load()
2017-12-14T11:33:02.729533+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2017-12-14T11:33:02.729534+00:00 app[web.1]:     return self.load_wsgiapp()
2017-12-14T11:33:02.729534+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2017-12-14T11:33:02.729534+00:00 app[web.1]:     return util.import_app(self.app_uri)
2017-12-14T11:33:02.729535+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 354, in import_app
2017-12-14T11:33:02.729535+00:00 app[web.1]:     __import__(module)
2017-12-14T11:33:02.729535+00:00 app[web.1]: ImportError: No module named candyland2.wsgi
2017-12-14T11:33:02.729595+00:00 app[web.1]: [2017-12-14 11:33:02 +0000] [9] [INFO] Worker exiting (pid: 9)
2017-12-14T11:33:02.746700+00:00 app[web.1]: Traceback (most recent call last):
2017-12-14T11:33:02.746707+00:00 app[web.1]:   File "/app/.heroku/python/bin/gunicorn", line 11, in <module>
2017-12-14T11:33:02.746755+00:00 app[web.1]:     sys.exit(run())
2017-12-14T11:33:02.746756+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
2017-12-14T11:33:02.746842+00:00 app[web.1]:     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
2017-12-14T11:33:02.746842+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 192, in run
2017-12-14T11:33:02.746891+00:00 app[web.1]:     super(Application, self).run()
2017-12-14T11:33:02.746892+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 72, in run
2017-12-14T11:33:02.746895+00:00 app[web.1]:     Arbiter(self).run()
2017-12-14T11:33:02.746897+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 179, in run
2017-12-14T11:33:02.746940+00:00 app[web.1]:     self.manage_workers()
2017-12-14T11:33:02.746941+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 482, in manage_workers
2017-12-14T11:33:02.747013+00:00 app[web.1]:     self.spawn_workers()
2017-12-14T11:33:02.747014+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 549, in spawn_workers
2017-12-14T11:33:02.747076+00:00 app[web.1]:     time.sleep(0.1 * random.random())
2017-12-14T11:33:02.747079+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 219, in handle_chld
2017-12-14T11:33:02.747120+00:00 app[web.1]:     self.reap_workers()
2017-12-14T11:33:02.747122+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 464, in reap_workers
2017-12-14T11:33:02.747188+00:00 app[web.1]:     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
2017-12-14T11:33:02.747249+00:00 app[web.1]: gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2017-12-14T11:33:07.930864+00:00 heroku[web.1]: Starting process with command `gunicorn candyland2.wsgi:application`
2017-12-14T11:33:10.427866+00:00 heroku[web.1]: State changed from starting to crashed
2017-12-14T11:33:10.421380+00:00 heroku[web.1]: Process exited with status 1
2017-12-14T11:33:10.329120+00:00 app[web.1]: [2017-12-14 11:33:10 +0000] [4] [INFO] Starting gunicorn 19.4.0
2017-12-14T11:33:10.329680+00:00 app[web.1]: [2017-12-14 11:33:10 +0000] [4] [INFO] Using worker: sync
2017-12-14T11:33:10.329561+00:00 app[web.1]: [2017-12-14 11:33:10 +0000] [4] [INFO] Listening at: http://0.0.0.0:45222 (4)
2017-12-14T11:33:10.334157+00:00 app[web.1]: [2017-12-14 11:33:10 +0000] [9] [INFO] Booting worker with pid: 9
2017-12-14T11:33:10.336372+00:00 app[web.1]: [2017-12-14 11:33:10 +0000] [9] [ERROR] Exception in worker process:
2017-12-14T11:33:10.336373+00:00 app[web.1]: Traceback (most recent call last):
2017-12-14T11:33:10.336374+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
2017-12-14T11:33:10.336375+00:00 app[web.1]:     worker.init_process()
2017-12-14T11:33:10.336376+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
2017-12-14T11:33:10.336376+00:00 app[web.1]:     self.load_wsgi()
2017-12-14T11:33:10.336377+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
2017-12-14T11:33:10.336378+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2017-12-14T11:33:10.336378+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
2017-12-14T11:33:10.336379+00:00 app[web.1]:     self.callable = self.load()
2017-12-14T11:33:10.336380+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2017-12-14T11:33:10.336380+00:00 app[web.1]:     return self.load_wsgiapp()
2017-12-14T11:33:10.336381+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2017-12-14T11:33:10.336382+00:00 app[web.1]:     return util.import_app(self.app_uri)
2017-12-14T11:33:10.336382+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 354, in import_app
2017-12-14T11:33:10.336383+00:00 app[web.1]:     __import__(module)
2017-12-14T11:33:10.336383+00:00 app[web.1]: ImportError: No module named candyland2.wsgi
2017-12-14T11:33:10.336384+00:00 app[web.1]: Traceback (most recent call last):
2017-12-14T11:33:10.336385+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
2017-12-14T11:33:10.336386+00:00 app[web.1]:     worker.init_process()
2017-12-14T11:33:10.336386+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
2017-12-14T11:33:10.336387+00:00 app[web.1]:     self.load_wsgi()
2017-12-14T11:33:10.336387+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
2017-12-14T11:33:10.336388+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2017-12-14T11:33:10.336389+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
2017-12-14T11:33:10.336389+00:00 app[web.1]:     self.callable = self.load()
2017-12-14T11:33:10.336390+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2017-12-14T11:33:10.336390+00:00 app[web.1]:     return self.load_wsgiapp()
2017-12-14T11:33:10.336391+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2017-12-14T11:33:10.336395+00:00 app[web.1]:     return util.import_app(self.app_uri)
2017-12-14T11:33:10.336396+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 354, in import_app
2017-12-14T11:33:10.336396+00:00 app[web.1]:     __import__(module)
2017-12-14T11:33:10.336397+00:00 app[web.1]: ImportError: No module named candyland2.wsgi
2017-12-14T11:33:10.336466+00:00 app[web.1]: [2017-12-14 11:33:10 +0000] [9] [INFO] Worker exiting (pid: 9)
2017-12-14T11:33:10.353882+00:00 app[web.1]: Traceback (most recent call last):
2017-12-14T11:33:10.353884+00:00 app[web.1]:   File "/app/.heroku/python/bin/gunicorn", line 11, in <module>
2017-12-14T11:33:10.353889+00:00 app[web.1]:     sys.exit(run())
2017-12-14T11:33:10.353892+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
2017-12-14T11:33:10.353920+00:00 app[web.1]:     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
2017-12-14T11:33:10.353921+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 192, in run
2017-12-14T11:33:10.353957+00:00 app[web.1]:     super(Application, self).run()
2017-12-14T11:33:10.353957+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 72, in run
2017-12-14T11:33:10.353977+00:00 app[web.1]:     Arbiter(self).run()
2017-12-14T11:33:10.353978+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 179, in run
2017-12-14T11:33:10.354016+00:00 app[web.1]:     self.manage_workers()
2017-12-14T11:33:10.354018+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 482, in manage_workers
2017-12-14T11:33:10.354075+00:00 app[web.1]:     self.spawn_workers()
2017-12-14T11:33:10.354076+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 549, in spawn_workers
2017-12-14T11:33:10.354142+00:00 app[web.1]:     time.sleep(0.1 * random.random())
2017-12-14T11:33:10.354143+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 219, in handle_chld
2017-12-14T11:33:10.354178+00:00 app[web.1]:     self.reap_workers()
2017-12-14T11:33:10.354178+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 464, in reap_workers
2017-12-14T11:33:10.354242+00:00 app[web.1]:     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
2017-12-14T11:33:10.354279+00:00 app[web.1]: gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2017-12-14T11:33:19.065511+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=candyland2.herokuapp.com request_id=cf9ba884-3945-445a-8128-5ae486bac32f fwd="2.25.81.139" dyno= connect= service= status=503 bytes= protocol=https
2017-12-14T11:33:21.462985+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=candyland2.herokuapp.com request_id=99f63bc0-7835-4d50-a9d9-423dfe69f7e9 fwd="2.25.81.139" dyno= connect= service= status=503 bytes= protocol=https
2017-12-14T11:35:05.385221+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=candyland2.herokuapp.com request_id=9901da83-0885-42b5-9d03-ab3e9a582b66 fwd="2.25.81.139" dyno= connect= service= status=503 bytes= protocol=https
2017-12-14T11:35:03.303863+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=candyland2.herokuapp.com request_id=2749b716-f778-45a3-9c0f-97a326a6e4ec fwd="2.25.81.139" dyno= connect= service= status=503 bytes= protocol=https
2017-12-14T11:35:23.071503+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=candyland2.herokuapp.com request_id=bc9de265-51f8-4909-b425-e91d3488eda9 fwd="2.25.81.139" dyno= connect= service= status=503 bytes= protocol=https
2017-12-14T11:35:23.319947+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=candyland2.herokuapp.com request_id=bc4ed434-be85-4f3d-b4b1-691c87abcf2e fwd="2.25.81.139" dyno= connect= service= status=503 bytes= protocol=https
